server:
  port: 4000
  logLevel: 1
  nodeEnv: production

redis:
  sub:
    host: redis-master
  pub:
    host: redis-master
  port: 6379
  password: redis

docker:
  secrets:
    region: eu-west-1
    name: docker.io/radixdlt

replicaCount: 2

image:
  repository: docker.io/radixdlt/signaling-server
  pullPolicy: IfNotPresent
  tag: ''

imagePullSecrets:
  - name: docker-hub-dev

nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: true
  annotations: {}
  name: ''

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 4000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/load-balance: "ewma"
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
       proxy_set_header Upgrade $http_upgrade;
       proxy_http_version 1.1;
       proxy_set_header X-Forwarded-Host $http_host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-For $remote_addr;
       proxy_set_header Host $host;
       proxy_set_header Connection "upgrade";
       proxy_cache_bypass $http_upgrade;
      }
  hosts:
    - host: signaling-server-dev.extratools.works
      paths:
        - path: /
          backend:
            serviceName: signaling-server
            servicePort: 4000
  tls:
    - hosts:
        - signaling-server-dev.extratools.works

javascriptHeap: 13000
resources:
  limits:
    memory: 6Gi
  requests:
    cpu: 1200m
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60

nodeSelector: {}

tolerations: []

affinity: {}

metrics:
  enabled: true
  port: 4001
  dashboard_url: "https://radixdlt.grafana.net/d/aegEXd97z/turn-server?orgId=1"
  serviceMonitor:
    path: /metrics
    interval: 15s
