helmDefaults:
  verify: false
  wait: false
  timeout: 600
  recreatePods: false
  force: false
  createNamespace: false
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: rdx-works
    url: https://raw.githubusercontent.com/radixdlt/helm-charts/master/
    username: {{ requiredEnv "HELM_GH_USER" }}
    password: {{ requiredEnv "HELM_GH_PASS" }}
environments:
  default: {}
  dev: {}
  pr: {}
  betanet: {}
releases:
{{ $SIG_SRV_NS := .Namespace }}
{{ $SIG_SRV_IMAGE_TAG := .StateValues.ci.tag }}
{{ $ENVIRONMENT_NAME := .Environment.Name }}
{{ $INSTALL_LOCAL_REDIS := ternary (eq $ENVIRONMENT_NAME "pr") true false }}

  - name: redis
    namespace: {{ $SIG_SRV_NS }}
    chart: bitnami/redis
    version: 16.10.1
    installed: {{ $INSTALL_LOCAL_REDIS }}
    values:
     - architecture: standalone
       commonConfiguration: |
         loglevel verbose
         client-output-buffer-limit normal 0 0 0
         client-output-buffer-limit slave 1024mb 128mb 60
         client-output-buffer-limit pubsub 1024mb 128mb 60
       auth:
         enabled: true
         password: redis
       master:
         resources:
           limits:
             cpu: 1000m
             memory: 512Mi
           requests:
             cpu: 1000m
             memory: 512Mi
         persistence:
           enabled: true
       replica:
         replicaCount: 4
       metrics:
         enabled: true
         serviceMonitor:
           enabled: true
           additionalLabels:
             release: prometheus-operator
  - name: turn-server
    namespace: {{ $SIG_SRV_NS }}
    chart: ./turn-server
    values:
      - environments/{{ .Environment.Name }}/turn-server-values.yaml.gotmpl
  - name: signaling-server
    namespace: {{ $SIG_SRV_NS }}
    chart: ./signaling-server
    values: 
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl
      - image:
          tag: {{ $SIG_SRV_IMAGE_TAG }}

  - name: developer-access
    namespace: {{ $SIG_SRV_NS}}
    chart: rdx-works/developer-access
    version: 1.0.0
    values:
      - project: signaling-server

  - name: alertmanager
    namespace: {{ $SIG_SRV_NS }}
    chart: rdx-works/alertmanager-configs
    installed: {{ ternary (eq $ENVIRONMENT_NAME "pr") false true }}
    version: 1.0.0
    values:
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl
