apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "turn-server.fullname" . }}-config
  labels:
    {{- include "turn-server.labels" . | nindent 4 }}
data:
  turnserver.conf: |
    log-file=stdout
    pidfile=/var/tmp/turnserver.pid
    listening-port={{ .Values.service.port }}
    realm={{ .Values.service.hostname.udp }}
    server-name=turnserver

    listening-ip=0.0.0.0
    fingerprint
    no-cli
    verbose
    no-tls
    no-dtls
