apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "turn-server.fullname" . }}-config
  labels:
    {{- include "turn-server.labels" . | nindent 4 }}
data:
  turnserver.conf: |
    log-file=stdout
    pidfile=/var/tmp/turnserver.pid
    listening-port={{ .Values.service.port }}
    realm=turn-dev.extratools.works

    redis-userdb="ip=redis-master.{{ .Release.Namespace }}.svc.cluster.local dbname=coturn password=redis port=6379 connect_timeout=30"

    fingerprint
    no-cli
