apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "turn-server.fullname" . }}
  labels:
    {{- include "turn-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "turn-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/coturn-config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      labels:
        {{- include "turn-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "turn-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: coturn-config
          configMap:
            name: {{ include "turn-server.fullname" . }}-config
        - name: tmp
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["-c", "/turnserver.conf", "--prometheus"]
          volumeMounts:
            - name: coturn-config
              mountPath: /turnserver.conf
              subPath: turnserver.conf
              readOnly: true
            - name: tmp
              mountPath: /var/tmp
          ports:
            - name: turn-tcp
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: turn-udp
              containerPort: {{ .Values.service.port }}
              protocol: UDP
            - name: metrics
              containerPort: 9641
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: metrics
          readinessProbe:
            tcpSocket:
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
