---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "turn-server.fullname" . }}-metrics
  labels:
    {{- include "turn-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      targetPort: metrics
      port: 9090
      protocol: TCP
  selector:
    {{- include "turn-server.selectorLabels" . | nindent 4 }}
