{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "turn-server.fullname" . }}
  labels:
    {{- include "turn-server.labels" . | nindent 4 }}
spec:
  groups:
  - name: TURN
    rules:
    - alert: NoTURNMetricsAvailable
      expr: absent(process_start_time_seconds{job="turn-server-metrics"})
      labels:
        severity: critical
        env: {{ .Values.metrics.environment }}
        tier: infrastructure
        application: signaling-server
        cluster: {{ .Values.metrics.cluster }}
        namespace: {{ .Release.Namespace }}
      for: 5m
      annotations:
        summary: "No TURN metrics available"
        description: "Metrics are not being collected for the TURN server"
        dashboard: {{ .Values.metrics.dashboard_url }}
        runbook_url: "https://runbooks.extratools.works"
{{- end }}
