---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "turn-server.fullname" . }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.hostname }}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  labels:
    {{- include "turn-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: turn-tcp
      targetPort: turn-tcp
      port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "turn-server.selectorLabels" . | nindent 4 }}
