apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "signaling-server.fullname" . }}
  labels:
    {{- include "signaling-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "signaling-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "signaling-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "signaling-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node"]
          args: ["--max-old-space-size=15360", "build/server.js"]
          env:
            - name: LOG_LEVEL
              value: {{ .Values.server.logLevel | quote }}
            - name: NODE_ENV
              value: {{ .Values.server.nodeEnv | quote }}
            - name: PORT
              value: {{ .Values.server.port | quote }}
            - name: HTTP_PORT
              value: {{ .Values.metrics.port | quote }}
            - name: REDIS_HOST_PUB
              value: {{ .Values.redis.pub.host | quote }}
            - name: REDIS_HOST_SUBS
              value: {{ .Values.redis.sub.host | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
#            - name: REDIS_PASSWORD
#              value: {{ .Values.redis.password | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.server.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 5
            httpGet:
              path: /health
              port: metrics
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 10
            httpGet:
              path: /health
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
