{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "signaling-server.fullname" . }}
  labels:
    release: prometheus-operator
spec:
  endpoints:
  - port: metrics
    path: {{ .Values.metrics.serviceMonitor.path }}
    interval: {{ .Values.metrics.serviceMonitor.interval }}
  selector:
    matchLabels:
      {{- include "signaling-server.labels" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "signaling-server.fullname" . }}-metrics
  labels:
    {{- include "signaling-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "signaling-server.selectorLabels" . | nindent 4 }}
{{- end }}
