helmDefaults:
  verify: false
  wait: false
  timeout: 600
  recreatePods: false
  force: false
  createNamespace: true
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
releases:
  - name: signaling-server-promtail
    namespace: signaling-server-promtail
    chart: grafana/promtail
    version: 3.6.0
    values:
      - extraArgs:
        - -client.url=https://{{ requiredEnv "LOKI_USER"}}:{{ requiredEnv "LOKI_PASSWORD" }}@{{ requiredEnv "LOKI_URL" }}
      - promtail.config
