name: Delete PR sub-namespace

on:
  pull_request:
    types: [ closed ]

jobs:
  delete-pr-namespace:
    permissions:
      id-token: write
      contents: read
      pull-requests: read

    runs-on: ubuntu-latest
    uses: radixdlt/iac-resuable-artifacts/.github/workflows/delete-pr-subns.yml@v0.2
    with:
      project_name: signaling-server
      pull_request_number: ${{ github.event.pull_request.number }}
      aws_region: eu-west-2
      role_to_assume: arn:aws:iam::308190735829:role/gh-signaling-server-pr-deployer
      eks_cluster: rdx-works-main-dev