name: deploy

on:
  workflow_call:
    inputs:
      env_name:
        description: 'The name of the environment to be deployed'
        required: true
        type: string
      image_tag:
        description: 'The image tag to be deployed'
        required: true
        type: string
      namespace:
        description: 'The namespace to be used for the deployment'
        required: true
        type: string
      create_subns:
        description: 'Whether to create a subnamespace'
        required: false
        default: ""
        type: string
      aws_region:
        description: "The AWS region that will be used on deployment"
        required: false
        default: "eu-west-2"
        type: string
      role_to_assume:
        description: "The IAM to be used for the EKS authentication"
        required: true
        default: ""
        type: string
      pr_number:
        description: 'The PR number'
        required: false
        default: ""
        type: string

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
      pull-requests: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.9.0
        with:
          helm-diff-plugin-version: "v3.1.3"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: ${{ inputs.aws_region }}

      - name: Deploy
        run: |
          aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER --alias $EKS_CLUSTER
          kubectl config get-contexts

          echo "Environment $ENVIRONMENT_NAME"
          echo "IMAGE_TAG=$IMAGE_TAG"
          echo "NS=$NS"

          cat <<DOC > subns-manifest.yaml
          apiVersion: hnc.x-k8s.io/v1alpha2
          kind: SubnamespaceAnchor
          metadata:
            name: $NS
            namespace: signaling-server-ci-pr
          DOC

          # Create subnamespace if we're deploying a pull request.
          if [ -n "${{ inputs.create_subns }}" ]; then
            cat subns-manifest.yaml
            kubectl apply -f subns-manifest.yaml
          fi

          cd deploy/helm
          helmfile --environment $ENVIRONMENT_NAME apply
        env:
          NS: ${{ inputs.namespace }}
          ENVIRONMENT_NAME: ${{ inputs.env_name }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          AWS_REGION: ${{ inputs.aws_region }}
          EKS_CLUSTER: rdx-works-main-dev
