name: load-testing
on:
  schedule:
    - cron:  '10 0 * * MON'

jobs:
  locust:
    permissions:
      id-token: write
      contents: read
      pull-requests: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: arn:aws:iam::308190735829:role/gh-signaling-server-load-testing-runner
          aws-region: eu-west-2

      - name: EKS cluster info
        run: |
          aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER --alias $EKS_CLUSTER
          kubectl config get-contexts
        env:
          AWS_REGION: eu-west-2
          EKS_CLUSTER: rdx-works-main-dev

      - name: Scale up the workers
        run: |
          kubectl scale deploy load-injector-worker -n load-injector-signaling-server --replicas 30
          kubectl rollout status deployment load-injector-worker -n load-injector-signaling-server

      - name: Run the load test
        run: |
          set -euo pipefail

          curl -XPOST -sfL -v -u "$LOCUST_USER:$LOCUST_PASS" https://signaling-lcst.extratools.works/swarm \
            -d "host=https://signaling-server-dev.rdx-works-main.extratools.works" \
            -d "spawn_rate=100" \
            -d "user_count=70000"

            sleep 600
        env:
          LOCUST_USER: ${{ secrets.LOCUST_USER }}
          LOCUST_PASS: ${{ secrets.LOCUST_PASS }}

      - name: Scale down the workers
        if: always()
        run: |
          kubectl scale deploy load-injector-worker -n load-injector-signaling-server --replicas 0
          kubectl rollout restart deploy load-injector-master -n load-injector-signaling-server
