name: Release Workflow
on:
  release:
    types: [released, prereleased]

jobs:
  deploy_mainnet:
    if: ${{ github.event_name == 'release' && github.event.release.prerelease == false }}
    uses: radixdlt/iac-resuable-artifacts/.github/workflows/deploy.yml@v0.8.3
    with:
      environment: mainnet
      app_name: signaling-server
      step_name: deploy-mainnet
      env_name: mainnet
      namespace: signaling-server-mainnet
      create_subns: false
      aws_region: eu-west-2
      role_to_assume: arn:aws:iam::821496737932:role/gh-signaling-server-mainnet-deployer
      eks_cluster: rtlj-prod
      helmfile_extra_vars: >-
        ci.tag=${{ github.event.release.tag_name }},
        ci.environment=mainnet

    deploy_kisharnet:
      if: ${{ github.event_name == 'release' && github.event.release.prerelease == true && contains(github.ref, 'rc-v1') }}
      uses: radixdlt/iac-resuable-artifacts/.github/workflows/deploy.yml@v0.8.3
      with:
        app_name: signaling-server
        environment: kisharnet
        step_name: deploy-kisharnet
        env_name: kisharnet
        namespace: signaling-server-kisharnet
        create_subns: false
        aws_region: eu-west-2
        role_to_assume: arn:aws:iam::821496737932:role/gh-signaling-server-kisharnet-deployer
        eks_cluster: rtlj-prod
        helmfile_extra_vars: >-
          ci.tag=${{ github.event.release.tag_name }},
          ci.environment=kisharnet

    deploy_ansharnet:
      if: ${{ github.event_name == 'release' && github.event.release.prerelease == true && contains(github.ref, 'rc-v2') }}
      uses: radixdlt/iac-resuable-artifacts/.github/workflows/deploy.yml@v0.8.3
      with:
        app_name: signaling-server
        environment: ansharnet
        step_name: deploy-ansharnet
        env_name: ansharnet
        namespace: signaling-server-ansharnet
        create_subns: false
        aws_region: eu-west-2
        role_to_assume: arn:aws:iam::821496737932:role/gh-signaling-server-ansharnet-deployer
        eks_cluster: rtlj-prod
        helmfile_extra_vars: >-
          ci.tag=${{ github.event.release.tag_name }},
          ci.environment=ansharnet